# Generated by Django 4.0.3 on 2022-03-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moi',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=6)),
            ],
        ),
    ]
