# Generated by Django 3.1.14 on 2022-06-13 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0007_auto_20220613_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 19, 25, 14, 923141)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 19, 25, 14, 901914)),
        ),
    ]
