# Generated by Django 3.1.14 on 2022-06-13 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0011_auto_20220613_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine',
            new_name='mach',
        ),
        migrations.AddField(
            model_name='moi',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moi',
            name='prenom',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infra',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 28, 56, 78531)),
        ),
        migrations.AlterField(
            model_name='infra',
            name='nb_machines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 28, 56, 57407)),
        ),
    ]
