# Generated by Django 3.1.14 on 2022-06-13 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0012_auto_20220613_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 38, 21, 360563)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 22, 38, 21, 340333)),
        ),
    ]
