# Generated by Django 3.1.14 on 2022-06-14 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0016_auto_20220613_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moi',
            name='age',
        ),
        migrations.AddField(
            model_name='machine',
            name='infrastructure',
            field=models.CharField(default='..', max_length=20),
        ),
        migrations.AddField(
            model_name='moi',
            name='adresse_mail',
            field=models.CharField(default='..', max_length=20),
        ),
        migrations.AddField(
            model_name='moi',
            name='password',
            field=models.CharField(default='..', max_length=30),
        ),
        migrations.AddField(
            model_name='moi',
            name='poste',
            field=models.CharField(default='..', max_length=20),
        ),
        migrations.AddField(
            model_name='moi',
            name='username',
            field=models.TextField(default='..', max_length=40),
        ),
        migrations.AlterField(
            model_name='infra',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 7, 35, 934396)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 7, 35, 913412)),
        ),
    ]
