# Generated by Django 3.1.14 on 2022-06-14 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0017_auto_20220614_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 16, 5, 164576)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 16, 5, 143622)),
        ),
        migrations.AlterField(
            model_name='moi',
            name='poste',
            field=models.TextField(default='..', max_length=40),
        ),
        migrations.AlterField(
            model_name='moi',
            name='username',
            field=models.CharField(default='..', max_length=40),
        ),
    ]
