# Generated by Django 3.1.14 on 2022-06-14 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0018_auto_20220614_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 17, 15, 248087)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 0, 17, 15, 228620)),
        ),
        migrations.AlterField(
            model_name='moi',
            name='adresse_mail',
            field=models.CharField(default='..', max_length=40),
        ),
    ]
