# Generated by Django 4.0.3 on 2022-06-14 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TD1App', '0019_auto_20220614_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='entretien',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 10, 8, 43, 12826)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 10, 8, 42, 991261)),
        ),
    ]
